In [2]:
import numpy as np

In [3]:
x = np.arange(1, 21)

In [4]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [5]:
x[8]

9

In [6]:
x[-1]

20

In [7]:
x[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [8]:
x[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [10]:
x[0:2]

array([1, 2])

In [11]:
y = x[5:15] = 40

In [12]:
y

40

In [13]:
x

array([ 1,  2,  3,  4,  5, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 16, 17,
       18, 19, 20])

In [14]:
y = x.copy()

In [15]:
y

array([ 1,  2,  3,  4,  5, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 16, 17,
       18, 19, 20])

In [16]:
# slicing and index in 2D arrays

In [17]:
x = np.arange(25).reshape(5,5)

In [18]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
x[2][2]

12

In [20]:
x[4][2]

22

In [21]:
x[2,2]

12

In [22]:
x[0:2,2:]

array([[2, 3, 4],
       [7, 8, 9]])

In [23]:
x[1:4, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [24]:
y = np.arange(1, 20)

In [25]:
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [26]:
y > 12                      # conditional selection

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [27]:
y[y > 12]

array([13, 14, 15, 16, 17, 18, 19])

In [29]:
y[y%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
y[y%2 != 0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])