In [4]:
import numpy as np

In [5]:
x = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
y = np.array(x)

In [8]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# Methods in Numpy

In [10]:
x = [1, 2, 3, 4, 5]

In [11]:
y = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(y)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.zeros(3)      # zero matrix

array([0., 0., 0.])

In [14]:
np.zeros((3,2))     # for multi dimensional

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
np.zeros((3,2))+5

array([[5., 5.],
       [5., 5.],
       [5., 5.]])

In [16]:
np.ones((3,4))           # Identity matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.eye(4)                   # diagonal element 1 with order 4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.arange(10)               # array of range[0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(10).reshape(2, 5)          # 2d array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
np.linspace(0,10, 5)            # linerly spaced integers b/w 0, 10 with 5 steps

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
x = np.array(x)

In [27]:
x.max()

5

In [28]:
x.min()

1

In [30]:
np.random.rand(5)            # 5 random +ve values

array([0.93481012, 0.39953592, 0.20344145, 0.3449538 , 0.99049732])

In [32]:
np.random.randn(5)              # 5 random -ve values

array([-1.67297702, -0.10785242, -0.25705972,  1.13389476,  0.41078921])

In [33]:
np.random.randint(1, 100)            # random integer b/w 1, 100

55

In [34]:
x.argmax()                      # index of max 

4

In [36]:
x.argmin()                     # index of min

0