In [1]:
import numpy as np

In [2]:
x = np.arange(10)

In [3]:
y = np.arange(10, 20)

In [4]:
z = x+y

In [5]:
z

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [6]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [7]:
np.cos(x)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [8]:
np.log(x)

c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [9]:
x = np.arange(12).reshape(3,4)

In [10]:
y = np.arange(10, 22).reshape(3,4)

In [13]:
x+y                        # order must be same

array([[10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [14]:
x*y

array([[  0,  11,  24,  39],
       [ 56,  75,  96, 119],
       [144, 171, 200, 231]])

In [15]:
x = np.arange(12)

In [16]:
x.sum()

66

In [17]:
np.full((3,3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
arr = np.arange(10)

In [19]:
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [20]:
arr[arr%2==1] = -1             # converts all odd number to -1

In [21]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [23]:
a = np.array([1,1,2,3,4,5,6])

In [24]:
b = np.array([0,2,1,3,4,8,9])

In [28]:
np.intersect1d(a,b)

array([1, 2, 3, 4])

In [29]:
a = np.arange(10)

In [30]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
a[(a>5) & (a<=10)]

array([6, 7, 8, 9])